services:
  - type: web
    name: engajamento-api
    env: python
    rootDir: apps/api
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn main:app --host 0.0.0.0 --port $PORT
    plan: free
    autoDeploy: true
    envVars:
      - key: DATABASE_URL
        sync: false

  - type: web
    name: engajamento-dashboard
    env: python
    rootDir: apps/dashboard
    buildCommand: pip install -r requirements.txt
    startCommand: streamlit run streamlit_app.py --server.port $PORT --server.address 0.0.0.0
    plan: free
    autoDeploy: true
    envVars:
      - key: DATABASE_URL
        sync: false

  - type: web
    name: dbt-runner
    env: python
    rootDir: apps/dbt_runner
    buildCommand: |
      pip install -r requirements.txt
      pip install dbt-postgres
    startCommand: uvicorn main:app --host 0.0.0.0 --port $PORT
    plan: free
    autoDeploy: true
    envVars:
      - key: DBT_HOST
        sync: false
      - key: DBT_USER
        sync: false
      - key: DBT_PASSWORD
        sync: false
      - key: DBT_PORT
        value: "5432"
      - key: DBT_DBNAME
        sync: false
      - key: DBT_RUN_TOKEN
        sync: false   # opcional: defina para proteger o endpoint